version: '2.0'
services:
  web:
    restart: always
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/usr/src/app
    command: /usr/local/bin/gunicorn --reload --log-level info -w 1 -b 0.0.0.0:5000 app:app
#    networks:
#      cloud:
#        aliases:
#          - web
  logs:
    restart: always
    build: ./logs
    command: curl -L http://web:5000/logs/

#networks:
#  cloud:
#    driver: bridge
